# SPDX-FileCopyrightText: 2021 Malte Kliemann, Ole Kliemann
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: macOS (install, test)
on:
  push:
    branches: master
  pull_request:
    branches:
    - master
    - develop
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install
      run: |
        pip install -r requirements.txt
        pip install .
    - name: Tests
      run: pytest -vv tests/
      env:
        CLANG_LIBRARY_FILE: /Library/Developer/CommandLineTools/usr/lib/libclang.dylib
