name: ci
on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: DrCpp/drmock-gen
      - name: fetch dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libclang-7-dev
          export CLANG_LIBRARY_FILE=/usr/lib/llvm-7/lib/libclang.so
          pip install flake8
          pip install reuse
      - name: check license stubs
        run: reuse lint
      - name: install
        run: |
          pip install -r requirements.txt
          pip install .
      - name: tests
        run: pytest -vv tests/
