# SPDX-FileCopyrightText: 2021 Malte Kliemann, Ole Kliemann
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: ci
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  check-license-stubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch dependencies
        run: pip install reuse
      - name: check licenses
        run: reuse lint
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libclang-7-dev
      - name: install
        run: |
          pip install -r requirements.txt
          pip install .
      - name: tests
        run: pytest -vv tests/
        env:
          CLANG_LIBRARY_FILE: /usr/lib/llvm-7/lib/libclang.so
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: -h
      - name: fetch dependencies
        run: choco install llvm
      - name: install
        run: |
          pip install -r requirements.txt
          pip install .
      - name: foo
        run: drmock-genfdjaklsjflk
      - name: tests
        run: pytest -vv tests/
        env:
          CLANG_LIBRARY_FILE: C:\Program Files\LLVM\bin\libclang.dll
